spring:
  profiles:
    active: dev
  application:
    name: SPRING-DATA-JPA-SAMPLE-DEV
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost/postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.Oracle12cDialect
logging:
  level:
    org:
      hibernate:
        type: trace